[package]
name = "apt-gen-list"
version = "0.1.2"
authors = ["eatradish <sakiiily@aosc.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
serde_json = "1.0"
serde_yaml = "0.8"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
url = "2.2"
attohttpc = { version = "0.16", features = ["native-tls"] }
lazy_static = "1.4"
log = "0.4"
indicatif = "0.16"
