[package]
name = "apt-gen-list"
version = "0.5.5-alpha.0"
authors = ["eatradish <sakiiily@aosc.io>", "liushuyu <liushuyu@aosc.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
serde_json = "1.0"
serde_yaml = "0.8"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
url = "2.2"
reqwest = "0.11"
lazy_static = "1.4"
log = "0.4"
indicatif = "0.16"
sha1 = "0.6"
os-release = "0.1"
indexmap = {version = "1.6", features = ["serde-1"]}
owo-colors = "3.0"
futures = "0.3"
tokio = {version = "^1", features = ["rt-multi-thread", "rt", "time"]}
nix = "0.23"
# i18n
i18n-embed = { version = "0.13", features = ["fluent-system", "desktop-requester"]}
i18n-embed-fl = "0.6"
rust-embed = "^6"
unic-langid = "0.9"

[build-dependencies]
clap ="2.33"

[features]
aosc = []
