[package]
name = "apt-gen-list"
version = "0.4.8-alpha.0"
authors = ["eatradish <sakiiily@aosc.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
serde_json = "1.0"
serde_yaml = "0.8"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
url = "2.2"
surf = "2.2.0"
lazy_static = "1.4"
log = "0.4"
indicatif = "0.16"
sha1 = "0.6"
os-release = "0.1"
indexmap = {version = "1.6", features = ["serde-1"]}
whoami = "1.1"
owo-colors = "2.0"
futures = "0.3"
tokio = {version = "1.7", features = ["rt-multi-thread", "rt", "time"]}

[build-dependencies]
clap ="2.33"
